### ISSUE TITLE
unique type example not syntax-highlighted at `user-defined-data-types/`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/website#12]
https://www.unison-lang.org/docs/language-reference/user-defined-data-types/

<img width="769" alt="image" src="https://user-images.githubusercontent.com/538571/153338837-4b78c552-ee13-48b6-a639-e0638efd82d1.png">

**Comment by aryairani** [comment]
and none are syntax-highlighted at https://www.unison-lang.org/docs/language-reference/unique-types/

**Comment by hojberg** [comment]
The difference here is whether single quotes or backticks were used I believe. We definitely want to syntax highlight the latter, but if its added with single quotes—I think @rlmark might be able to elaborate on the reasoning there, but my understanding is that we sometimes want to render code in a deliberate way in docs, which we might loose via the pretty printer—in any regard, when the code hasn't been through the pretty printer we don't know enough about it to do links to terms and types etc.

**Comment by rlmark** [comment]
I updated the unique types to be clickable, but the challenge with the structural type examples is that they are structurally identical and only one gets rendered to the docs page even though you can refer to the structural type with either name.
