### ISSUE TITLE
`base.List.map` / `util.List.map` not monospace for some reason in `suffixed-based-name-resolution`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/website#15]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/538571/153339582-421287a8-36b5-4a8e-92d1-898de43586fc.png">

Also, is it "suffixed-based name resolution" or "suffix-based name resolution" or "suffixed name resolution"?

**Comment by hojberg** [comment]
this looks like its due to using ` instead of '', I make this mistake constantly

**Comment by hojberg** [comment]
cc @rlmark

**Comment by rlmark** [comment]
Fix has been deployed to prod.
