### ISSUE TITLE
Changes to "Documenting Unison Code"

### ISSUE THREAD

**Issue by brianloveswords** [unisonweb/website#31]
Hello! Chatted about this in Slack with @rlmark:

- added note about including a blank line before code blocks ![image](https://user-images.githubusercontent.com/166258/176303893-0f5e9dde-1a60-405e-be18-b8e0aab0ae06.png)

- added heading to list of supported syntax  ![image](https://user-images.githubusercontent.com/166258/176304525-4382d687-cf2c-4798-85be-32b156dbe640.png)

- fixed the formatting on {Some} in the Link syntax cheat sheet.  ![image](https://user-images.githubusercontent.com/166258/176304395-4f409d4e-e0f0-4524-8fea-69699cd004b5.png)

Here's the gist:
```
.learn.usageTopics> gist git@github.com:brianloveswords/unison-website:.gists
  Checking out main ...
  Synced 3 entities.                       
  Gist created. Pull via:
  
    pull git@github.com:brianloveswords/unison-website:#uu64bhtcd6
```

**Comment by rlmark** [comment]
Awesome! Thanks @brianloveswords. This change has been deployed in prod.
