### ISSUE TITLE
Broken link in Abilities doc

### ISSUE THREAD

**Issue by hojberg** [unisonweb/website#39]
> Reading https://www.unison-lang.org/learn/fundamentals/abilities/using-abilities-pt1/
> But clicking the link at the bottom of the page to go to part two gives me a 404.
> The link is https://www.unison-lang.org/learn%7B#0dtn1o2gj4}
> Whereas the link in the popup menu is https://www.unison-lang.org/learn/fundamentals/abilities/using-abilities-pt2

Reported in Slack by Martin G

**Comment by rlmark** [comment]
Thank you! Fixed in prod!
