### ISSUE TITLE
Mismatch in The Big Idea

### ISSUE THREAD

**Issue by jackie-scholl** [unisonweb/website#40]
I'm not sure which way it's supposed to go, but at the moment the article The Big Idea talks about `increment` but includes the source for two implementations of `isEven`:
![image](https://user-images.githubusercontent.com/1465656/193421769-3f152654-b1a3-4db5-971f-a05f7cae3122.png)
https://www.unison-lang.org/learn/the-big-idea/

**Comment by rlmark** [comment]
Thank you @jackie-scholl! We had an issue where Unison code snippets were getting swapped with one another in the `Doc` format. I've created a workaround to render the appropriate code samples, so the actual "increment" function should be showing up now!
