### ISSUE TITLE
404 for index.html

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/website#41]
I revisited the site (it's been too long!) and was surprised to get a 404 for index.html: 

![image](https://user-images.githubusercontent.com/633283/196032960-5cf3ca8a-67b4-434b-9c69-fd9c5f0cc8f0.png)

**Comment by rlmark** [comment]
Hi @philderbeast! Welcome back! 🎉 The old website is now deprecated and its new home is at https://www.unison-lang.org/.
