### ISSUE TITLE
Install steps for Linux on Unison website broken

### ISSUE THREAD

**Issue by cobaltburn** [unisonweb/website#71]
I was just reinstalling the ucm and I used the the command on the website.
The current URL used to download the ucm leads to a dead end.

https://github.com/unisonweb/unison/releases/download/latest/ucm-linux.tar.gz

switching it to the URL for the most current edition works just fine.

https://github.com/unisonweb/unison/releases/download/release%2F0.5.13/ucm-linux.tar.gz

**Comment by rlmark** [comment]
Thank you so much for reporting! I've redeployed the website with updated URLs.

**Comment by ceedubs** [comment]
To anyone who stumbles upon this, the following link should work for `latest`: `curl -L https://github.com/unisonweb/unison/releases/latest/download/ucm-linux.tar.gz`
