### ISSUE TITLE
Quickstart Ubuntu installation instructions are broken

### ISSUE THREAD

**Issue by pmarches** [unisonweb/website#82]
When following the ubuntu installation instructions in the [quickstart](https://www.unison-lang.org/docs/quickstart/)

curl downloads the http URL. This should be changed to https. 

The server will reply with a redirect to https, that curl will not follow. This causes an empty gpg key to be installed, which in turn will not authenticate the repository, which in turn will not install unisonweb.

**Comment by rlmark** [comment]
Thank you @pmarches, taking a look now!

**Comment by rlmark** [comment]
Thank you @pmarches, I believe these contributions (deployed yesterday) should fix the issue. Let me know if you're still running into issues and we can reopen this ticket. 

https://share.unison-lang.org/@unison/website/contributions/13
https://share.unison-lang.org/@unison/website/contributions/14
